### ISSUE TITLE
PouchDB 6.4.2 - TypeError: winningRev is not a function

### ISSUE THREAD

**Issue by lucapale** [pouchdb-community/pouchdb-adapter-cordova-sqlite#84]
### Issue
I am using PouchDB in a Ionic app.
With PouchDB 6.3.4 I was using the SQLite adapter for iOS. After upgrading to 6.4.2 I get this error and the db does not work:

Error in Success callbackId: SQLitePlugin1932871848 : TypeError: winningRev is not a function. (In 'winningRev(docInfo.metadata)', 'winningRev' is undefined)

### Info
- Environment: Ionic app
- Platform: iOS
- Adapter: pouchdb-adapter-cordova-sqlite with cordova-plugin-sqlite-2
- Server: Couchbase

### Reproduce
Use pouchdb-adapter-cordova-sqlite in iOS app with 6.4.2.

**Comment by mnewmedia** [comment]
This was a PouchDB Issue [7054](https://github.com/pouchdb/pouchdb/issues/7054) and is solved with PouchDB 6.4.3. So you can close this issue.

**Comment by paolosanchi** [comment]
I confirm, https://github.com/pouchdb-community/pouchdb-adapter-cordova-sqlite/pull/79 still need to be applied

**Comment by yurimorini** [comment]
Same here, I confirm you need to update pouchdb-core to the latest version available (6.4.3 at the moment)

**Comment by JasonAsmk** [comment]
Still getting this error on pouchdb 6.4.3 and pouchdb-adapter-cordova-sqlite 2.0.2 .
